#!/bin/bash

shpath=/var/tellme/stock/sh
szpath=/var/tellme/stock/sz
shlist=$(ls $shpath)
szlist=$(ls $szpath)

for i in $szlist; do 
	inosz="${i#sz}"
	result="${inosz%.day}"
	sed -i 's/\ /,/g' $szpath/$i
	sed_command=$(printf 's/^/%s,/g' "$result")
	sed -i "$sed_command" "$szpath/$i"
	sed -i -E 's/([0-9]{4})([0-9]{2})([0-9]{2})/\1-\2-\3/' $szpath/$i
	echo $i $(head -1  $szpath/$i)
done

for i in $shlist; do 
	inosh="${i#sh}"
	result="${inosh%.day}"
	sed -i 's/\ /,/g' $shpath/$i
	sed_command=$(printf 's/^/%s,/g' "$result")
	sed -i "$sed_command" "$shpath/$i"
	sed -i -E 's/([0-9]{4})([0-9]{2})([0-9]{2})/\1-\2-\3/' $shpath/$i
	echo $i $(head -1  $shpath/$i)
done
